# Generated by Django 4.1.4 on 2022-12-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO shop_collection (title)
            VALUES ('collection1')
        """, """
            DELETE FROM shop_collection
            WHERE title="collection1"
        """)
    ]
