# Generated by Django 4.1.7 on 2023-03-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_history', 'Can view history')]},
        ),
    ]
